name: Update all competitions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update_competition:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        competitionId: [ 25465, 25464, 25463, 25462, 25461 ]
    steps:
      - run: >
          curl -X POST https://api.wiseoldman.net/v2/competitions/${{ matrix.competitionId }}/update-all 
          -H "Content-type: application/json" 
          -d '{ "verificationCode": "${{ secrets.CODE }}" }'
        